name: Перевірка версій програмного забезпечення

on: [push]

jobs:
  print-software-versions:
    runs-on: ubuntu-latest
    steps:
    - name: Перевірка версій ОС та базового ПЗ
      run: |
        echo "Версія ОС:"
        lsb_release -a
        echo ""
        echo "Версія Python:"
        python --version
        echo ""
        echo "Версія Git:"
        git --version

  print-dbms-versions:
    needs: print-software-versions
    runs-on: ubuntu-latest
    steps:
    - name: Встановлення та перевірка PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql
        echo "Версія PostgreSQL:"
        psql --version
